spring:
  application:
    name: graphql-diet-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true

  #JPA/Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    com.graphql.execution: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE




